// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNGaRzLZNOvb9VPp_frfd-iP0757NejE',
    appId: '1:452481976231:android:b0aa4c2be60fefce631882',
    messagingSenderId: '452481976231',
    projectId: 'flutter-test-da806',
    storageBucket: 'flutter-test-da806.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3IzC09mXAQOjy3NTySJfcu-E2GANR4tM',
    appId: '1:452481976231:web:48d748d6a68c1368631882',
    messagingSenderId: '452481976231',
    projectId: 'flutter-test-da806',
    authDomain: 'flutter-test-da806.firebaseapp.com',
    storageBucket: 'flutter-test-da806.firebasestorage.app',
    measurementId: 'G-80KVJ8VPWG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKlTe2Qd4Vma59zjukBgMBrQxc8Fh5njo',
    appId: '1:452481976231:ios:538cbc3291bd1b1a631882',
    messagingSenderId: '452481976231',
    projectId: 'flutter-test-da806',
    storageBucket: 'flutter-test-da806.firebasestorage.app',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKlTe2Qd4Vma59zjukBgMBrQxc8Fh5njo',
    appId: '1:452481976231:ios:538cbc3291bd1b1a631882',
    messagingSenderId: '452481976231',
    projectId: 'flutter-test-da806',
    storageBucket: 'flutter-test-da806.firebasestorage.app',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3IzC09mXAQOjy3NTySJfcu-E2GANR4tM',
    appId: '1:452481976231:web:5cf817c44d697004631882',
    messagingSenderId: '452481976231',
    projectId: 'flutter-test-da806',
    authDomain: 'flutter-test-da806.firebaseapp.com',
    storageBucket: 'flutter-test-da806.firebasestorage.app',
    measurementId: 'G-N2HWQ303DV',
  );

}